Automate snapshots
cloudreach/aws-lambda-es-cleanup pull request #35
Opened 2019-12-05 18:43 UTC by fllaca

Creates a snapshot before deleting an index.

Snapshots are also rotated every `snapshot_delete_after` days

2019-12-05 18:44 UTC, fllaca commented
Closes #35

2019-12-06 10:08 UTC, giuliocalzolari commented
hi @fllaca looks great!
I will test as soon as possible!

2020-03-09 09:29 UTC, giuliocalzolari commented
Hi @fllaca we're testing a new version of the code, as soon as #37 is merged I will adapt the login to your code.

2020-04-27 07:30 UTC, giuliocalzolari commented
hi @fllaca I've finally merged the PR #37 and also upload the `tests` folder on #41 
In this way, people can spin-up a new cluster using terraform to test the new functionality

due to recent PR there is now some little conflicts can you please have a look?

2020-04-27 07:31 UTC, giuliocalzo requested changes
can you please update with the latest master?

2025-04-24 12:07 UTC, closed without merging