Fix Logic, Improve Test Coverage, and Resilience
cloudreach/aws-lambda-es-cleanup pull request #37
Opened 2019-12-17 20:19 UTC by johannes-gehrs

- When using an incorrect date pattern for the index format, the comparison of date stings meant that incorrect results could occur. This has lead to unintended deletion of data in our environment. This PR fixes this by comparing Python Date objects instead.
- It looks to me like the use of `<=` in the comparison meant that one more day than intended was deleted. See code.
- The decision logic is factored out into a pure function which is easily testable.
- Some unit tests have been added.
- In order to be able to import the module from the unit test file, I needed to rename the file. Module names with dashes cannot be easily imported.

2019-12-18 10:03 UTC, giuliocalzolari commented
Hi @johannes-gehrs thanks for your PR.
can I ask you why do you use a local function https://github.com/cloudreach/aws-lambda-es-cleanup/pull/37/files#diff-aedd2d570ffd28f6b0994ddd7fd88cddR155?

the method that you implement looks great and also allow to implement the unittest, but could we create a new method of the main class `ES_Cleanup` ?
is there any specific reason why you use a local function `should_delete`?

2019-12-18 15:51 UTC, johannes-gehrs commented
If it is a method than you always need to mock "god object" `ES_Cleanup ` in unit tests.

It is doable and if you insist I could refactor to that but I personally like normal functions, especially when we generally think about "pure logic" like we do here. 😄

2020-01-06 12:50 UTC, johannes-gehrs commented
If you are uncomfortable with the higher order function (not sure if that is the case)  it would be relatively easy to refactor this to use a normal `Decider` class which instances get initialized with the values we now pass to `delete_decider`.  And then we can call a method `decide` on the class instance.

2020-01-08 10:38 UTC, giuliocalzolari commented
having a class Decider would be awesome!

2020-01-21 13:32 UTC, giuliocalzolari commented
@johannes-gehrs  did you have some time to create the `Decider` class?

2020-01-24 15:02 UTC, johannes-gehrs commented
Sorry for the long delay. I have refactored to a class. Everything else should have stayed the same but do you have a way to test before merging and releasing?

2020-01-24 16:31 UTC, giuliocalzolari commented
Yes I have a script to deploy aws es and create multiple indexes to test it. Right now I deploy only for big changes.

2020-03-06 16:31 UTC, johannes-gehrs commented
Let's get this merged?

2020-03-09 09:13 UTC, giuliocalzolari commented
@johannes-gehrs I found some minor issue in the code, I've opened a PR on your repo
can you have a look?
https://github.com/johannes-gehrs/aws-lambda-es-cleanup/pull/1

2020-03-16 14:29 UTC, giuliocalzolari commented
@johannes-gehrs did you have a chance to review it?

2020-03-22 15:38 UTC, giuliocalzolari commented
@johannes-gehrs

2020-04-21 15:56 UTC, giuliocalzo requested changes
can you please merge my minor changes
https://github.com/johannes-gehrs/aws-lambda-es-cleanup/pull/1

2020-04-21 15:56 UTC, giuliocalzo requested changes
can you please merge my minor changes
https://github.com/johannes-gehrs/aws-lambda-es-cleanup/pull/1

2020-04-21 15:56 UTC, giuliocalzo requested changes
can you please merge my minor changes
https://github.com/johannes-gehrs/aws-lambda-es-cleanup/pull/1

2020-04-21 16:07 UTC, giuliocalzo requested changes
I've done some minor change 
here https://github.com/johannes-gehrs/aws-lambda-es-cleanup/pull/1
can you merge you your branch?

2020-04-22 06:55 UTC, giuliocalzo approved these changes

2020-04-22 06:55 UTC, merged